USE p9g5;
GO

CREATE SCHEMA PROJETO;
GO

CREATE TABLE PROJETO.Instituicao (
	
	id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR NOT NULL,
	descricao VARCHAR NOT NULL

);

GO

CREATE TABLE PROJETO.TipoTarefa (
	
	id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	designacao VARCHAR NOT NULL

);

GO

CREATE TABLE PROJETO.Aluno (
	
	email VARCHAR NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR NOT NULL,
	data_nascimento DATE NOT NULL

);

GO

CREATE TABLE PROJETO.Cadeira (
	
	codigo BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR NOT NULL,
	link VARCHAR NOT NULL,
	ano YEAR NOT NULL,
	semestre INT,
	nota_final FLOAT,
	aluno VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Aluno(email) 

);

GO

CREATE TABLE PROJETO.Grupo (
	
	codigo BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR NOT NULL,
	cadeira BIGINT NOT NULL FOREIGN KEY REFERENCES PROJETO.Cadeira(codigo)

);

GO

CREATE TABLE PROJETO.Tarefa (
	
	id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	titulo VARCHAR NOT NULL,
	descricao VARCHAR NOT NULL,
	completada_ts DATETIME NOT NULL,
	data_inicio DATE NOT NULL,
	data_final DATE NOT NULL,
	tipoTarefa BIGINT NOT NULL FOREIGN KEY REFERENCES PROJETO.TipoTarefa(id),
	aluno VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Aluno(email),
	cadeira BIGINT NOT NULL FOREIGN KEY REFERENCES PROJETO.Cadeira(codigo)

);

GO

CREATE TABLE PROJETO.Pagina (
	
	id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	titulo VARCHAR NOT NULL,
	aluno VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Aluno(email),
	cadeira BIGINT NOT NULL FOREIGN KEY REFERENCES PROJETO.Cadeira(codigo)

);

GO

CREATE TABLE PROJETO.Ficheiro (
	
	id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR NOT NULL,
	localizacao VARCHAR NOT NULL,
	aluno VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Aluno(email),
	related_to (??????????????)

);

GO

CREATE TABLE PROJETO.Professor (

	email VARCHAR NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR NOT NULL,
	instituicao BIGINT NOT NULL FOREIGN KEY REFERENCES PROJETO.Instituicao(id)

);

GO

CREATE TABLE PROJETO.ProfessorCadeira (

	professor VARCHAR NOT NULL IDENTITY(1,1) PRIMARY KEY FOREIGN KEY REFERENCES PROJETO.Professor(email),
	cadeira BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY FOREIGN KEY REFERENCES PROJETO.Cadeira(cadeira)

);

GO

CREATE TABLE PROJETO.GrupoProfessor (

	grupo BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY FOREIGN KEY REFERENCES PROJETO.Grupo(codigo),
	professor VARCHAR NOT NULL IDENTITY(1,1) PRIMARY KEY FOREIGN KEY REFERENCES PROJETO.Professor(email)

);

GO

CREATE TABLE PROJETO.GrupoAluno (

	grupo BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY FOREIGN KEY REFERENCES PROJETO.Grupo(codigo),
	aluno VARCHAR NOT NULL IDENTITY(1,1) PRIMARY KEY FOREIGN KEY REFERENCES PROJETO.Aluno(email)

);

GO