USE p9g5;
GO

CREATE SCHEMA PROJETO;
GO

CREATE TABLE PROJETO.Criador (
	
	codigo VARCHAR NOT NULL IDENTITY(1,1) PRIMARY KEY

);

GO

CREATE TABLE PROJETO.Instituicao (
	
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR NOT NULL,
	descricao VARCHAR NOT NULL

);

GO

CREATE TABLE PROJETO.TipoTarefa (
	
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	designacao VARCHAR NOT NULL

);

GO

CREATE TABLE PROJETO.Aluno (
	
	email VARCHAR NOT NULL PRIMARY KEY,
	nome VARCHAR NOT NULL,
	password VARCHAR NOT NULL, -- ALTERAR NO DER E NO ER
	data_nascimento DATE

);

GO

CREATE TABLE PROJETO.Cadeira (
	
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR NOT NULL,
	link VARCHAR,
	ano INT,
	semestre INT,
	nota_final FLOAT,
	aluno VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Aluno(email),
	codigo_criador VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Criador(codigo)

);

GO

CREATE TABLE PROJETO.Grupo (
	
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR NOT NULL,
	cadeira INT NOT NULL FOREIGN KEY REFERENCES PROJETO.Cadeira(id),
	codigo_criador VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Criador(codigo)

);

GO

CREATE TABLE PROJETO.Tarefa (
	
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	titulo VARCHAR NOT NULL,
	descricao VARCHAR,
	completada_ts DATETIME,
	data_inicio DATE,
	date_final DATE,
	tipoTarefa INT NOT NULL FOREIGN KEY REFERENCES PROJETO.TipoTarefa(id),
	aluno VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Aluno(email),
	cadeira INT FOREIGN KEY REFERENCES PROJETO.Cadeira(id),		-- 
	codigo_criador VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Criador(codigo)

);

GO

CREATE TABLE PROJETO.Pagina (
	
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	titulo VARCHAR NOT NULL,
	aluno VARCHAR FOREIGN KEY REFERENCES PROJETO.Aluno(email),
	cadeira INT FOREIGN KEY REFERENCES PROJETO.Cadeira(id), --
	codigo_criador VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Criador(codigo)

);

GO

CREATE TABLE PROJETO.Ficheiro (
	
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR NOT NULL,
	localizacao VARCHAR NOT NULL,
	aluno VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Aluno(email),
	codigo_criador VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Criador(codigo)

);

GO

CREATE TABLE PROJETO.Professor (

	email VARCHAR NOT NULL PRIMARY KEY,
	nome VARCHAR NOT NULL,
	instituicao INT NOT NULL FOREIGN KEY REFERENCES PROJETO.Instituicao(id)

);

GO

CREATE TABLE PROJETO.ProfessorCadeira (

	professor VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Professor(email),
	cadeira INT NOT NULL FOREIGN KEY REFERENCES PROJETO.Cadeira(id)

);

GO

CREATE TABLE PROJETO.GrupoProfessor (

	grupo INT NOT NULL FOREIGN KEY REFERENCES PROJETO.Grupo(id),
	professor VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Professor(email)

);

GO

CREATE TABLE PROJETO.GrupoAluno (

	grupo INT NOT NULL FOREIGN KEY REFERENCES PROJETO.Grupo(id),
	aluno VARCHAR NOT NULL FOREIGN KEY REFERENCES PROJETO.Aluno(email)

);

GO